# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cloud domaci

on:
  pull_request:
    branches:
      - main
      - master
    types: [closed]
  workflow_dispatch: # Allow manual triggering of workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Verify build
      run: |
        npm run build
        build_exit_code=$?
        if [ $build_exit_code -eq 0 ]; then
          echo "Build successful!"
        else
          echo "Build failed: Exit code $build_exit_code"
          exit $build_exit_code
        fi
  release:
    runs-on: windows-latest
    needs: [build] # Ensure the build job completes before creating a release
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Release Please Action
      uses: GoogleCloudPlatform/release-please-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
